#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

repo_dir="$(readlink -f "$(dirname "${0}")/..")"
cd $repo_dir

apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing hub
apk add make

"${repo_dir}/.ci/prepare_gituser.py"
chmod 600 "${HOME}/.ssh/id_rsa"
username=$(cat ${HOME}/github_user)
user_token=$(cat ${HOME}/github_token)
user_email=$(cat ${HOME}/github_email)

git config --global user.email "${username}"
git config --global user.name "${user_email}"

"${repo_dir}/.ci/write_docker_cfg.py"

# final setup for buildx
docker buildx create --use

BUILD_CD="yes" GITHUB_USER="${username}" GITHUB_TOKEN="${user_token}" "${repo_dir}/.ci/check-and-release"
