#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# set up component-cli
TEMP_DIR="$(mktemp -d)"
FILE_NAME="componentcli-linux-amd64"
OUT_FILE="${TEMP_DIR}/${FILE_NAME}.gz"
curl -L https://github.com/gardener/component-cli/releases/latest/download/componentcli-linux-amd64.gz -o "${OUT_FILE}"
gzip -d "${OUT_FILE}"
chmod +x "${TEMP_DIR}/${FILE_NAME}"
mv "${TEMP_DIR}/${FILE_NAME}" /usr/bin/component-cli
# as of time of writing, we have a "replacement" component-cli in place in the job-image that takes precedence since it is
# found first in $PATH. Therefore we have to update $PATH as well here
export PATH="/usr/bin:${PATH}"

VERSION="$1"
COMMIT="$2"

component_archive_path="$(mktemp -d)"
ctf_path="$(mktemp -d)"

cat << EOF > "${component_archive_path}/component-descriptor.yaml"
component:
  componentReferences: []
  labels: []
  name: github.com/gardener/hyperkube
  provider: internal
  repositoryContexts:
  - baseUrl: eu.gcr.io/sap-se-gcr-k8s-private/cnudie/gardener/development
    componentNameMapping: urlPath
    type: ociRegistry
  resources:
  - access:
      imageReference: eu.gcr.io/gardener-project/hyperkube:${VERSION}
      type: ociRegistry
    digest: null
    extraIdentity: {}
    labels: []
    name: hyperkube
    relation: local
    srcRefs: []
    type: ociImage
    version: ${VERSION}
  sources:
  - access:
      commit: ${COMMIT}
      ref: refs/tags/${VERSION}
      repoUrl: github.com/gardener/hyperkube
      type: github
    extraIdentity: {}
    labels:
    - name: cloud.gardener/cicd/source
      value:
        repository-classification: main
    name: github_com_gardener_hyperkube
    type: git
    version: ${VERSION}
  version: ${VERSION}
meta:
  schemaVersion: v2
signatures: []
EOF

tar cf "${component_archive_path}/ca" "component-descriptor.yaml" -C "${component_archive_path}"
tar cf "${ctf_path}/ctf" "ca" -C "${component_archive_path}"
component-cli ctf push "${ctf_path}/ctf"
