#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! which component-cli > /dev/null; then
  echo "Can't find 'component-cli' PATH. See https://github.com/gardener/component-cli for information on how to install it."
  exit 1
fi

VERSION="$1"
COMMIT="$2"

component_archive_path="$(mktemp -d)"
ctf_path="$(mktemp -d)"

cat << EOF > "${component_archive_path}/component-descriptor.yaml"
component:
  componentReferences: []
  labels: []
  name: github.com/gardener/hyperkube
  provider: internal
  repositoryContexts:
  - baseUrl: eu.gcr.io/sap-se-gcr-k8s-private/cnudie/gardener/development
    componentNameMapping: urlPath
    type: ociRegistry
  resources:
  - access:
      imageReference: eu.gcr.io/gardener-project/hyperkube:${VERSION}
      type: ociRegistry
    digest: null
    extraIdentity: {}
    labels: []
    name: hyperkube
    relation: local
    srcRefs: []
    type: ociImage
    version: ${VERSION}
  sources:
  - access:
      commit: ${COMMIT}
      ref: refs/tags/${VERSION}
      repoUrl: github.com/gardener/hyperkube
      type: github
    extraIdentity: {}
    labels:
    - name: cloud.gardener/cicd/source
      value:
        repository-classification: main
    name: github_com_gardener_hyperkube
    type: git
    version: ${VERSION}
  version: ${VERSION}
meta:
  schemaVersion: v2
signatures: []
EOF

tar cf "${component_archive_path}/ca" "component-descriptor.yaml" -C "${component_archive_path}"
tar cf "${ctf_path}/ctf" "ca" -C "${component_archive_path}"
component-cli ctf push "${ctf_path}/ctf"
