#!/usr/bin/env bash

if ! which gardener-ci &> /dev/null; then
  echo "Error: must install `gardener-cicd-cli` python package"
  exit 1
fi

if [ ! -d "$HOME/.docker" ]; then
  mkdir -p "$HOME/.docker"
fi

gardener-ci docker cfg \
  --image europe-docker.pkg.dev/gardener-project/releases/hyperkube \
  > $HOME/.docker/config.json
