on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build-and-publish-hyperkube-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: gardener/cc-utils/.github/actions/oci-auth@v1
        with:
          oci-image-reference: europe-docker.pkg.dev/gardener-project/releases/hyperkube
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@v1
      - uses: gardener/cc-utils/.github/actions/setup-git-identity@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.3.0
      - name: build-and-publish-hyperkube-images
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -euo pipefail
          .ci/check-and-release
